# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='long_description',
            field=models.CharField(default='Description not added.', max_length=1500),
        ),
    ]
