# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 02:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20171112_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='user_solved',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_solved', to=settings.AUTH_USER_MODEL),
        ),
    ]
