# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_auto_20171112_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
