# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20171124_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='image',
            field=models.ImageField(upload_to='media/_uploads/'),
        ),
    ]
