# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_auto_20171126_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='problem_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
