# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0014_solution_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='link',
        ),
    ]
