# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0015_remove_solution_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='likes',
        ),
        migrations.AlterField(
            model_name='problem',
            name='long_description',
            field=models.CharField(max_length=1500),
        ),
    ]
