# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
