# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 01:13
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credential',
            field=oauth2client.contrib.django_util.models.CredentialsField(null=True),
        ),
    ]
