# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 22:33
from __future__ import unicode_literals

from django.db import migrations
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credential',
            field=oauth2client.contrib.django_util.models.CredentialsField(blank=True, null=True),
        ),
    ]
