# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171204_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/_uploads/'),
        ),
    ]
