# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersConnected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
            ],
        ),
    ]
