version: 2
jobs:
  build:
    working_directory: ~/problem_solvent
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Installing Dependencies
          command: |
            yarn install
            sudo apt-get install postgresql-client

      - run:
          name: Running Test
          command: |
            psql -c "create database test" -U postgres -h localhost -p 5432
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: tr1